# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mabreu <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/19 17:04:09 by mabreu            #+#    #+#              #
#    Updated: 2017/08/20 09:22:48 by mabreu           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = colle-2

SRC = main.c 

all: $(NAME)

$(NAME)
	gcc -o $(NAME) $(SRC)

clean:
	./rm -rf *.o

fclean: clean
	./rm -f $(NAME)

res: fclean all














#./colle-00: ./colle-0
#		./colle-00
#colle-00.o: colle-00.c
#	gcc -o colle-00.o colle-00.c

#colle-01: colle_01.o main.o
#	gcc -o colle-01 colle-01.o main.o

#colle-01.o: colle-01.c
#	gcc -o colle-01.o colle-01.c

#colle-02: colle-02.o main.o
#	gcc -o colle-02 colle-02.o main.o

#colle-02.o: colle-02.c
#	gcc -o colle-02.o colle-02.c

#colle-03: colle-03.o main.o
#	gcc -o colle-03 colle-03.o main.o

#colle-03.o: colle-03.c
#	gcc -o colle-03.o colle-03.c

#colle-04: colle-04.o main.o
#	gcc -o colle-04 colle-04.o main.o

#colle-04.o: colle-04.c
#	gcc -o colle-04.o colle-04.c

#main.o: main.c
#	gcc -o main.o main.c
